In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('dm-csv-001/ufc-fighters-statistics.csv')
df.head()

,name,nickname,wins,losses,draws,height_cm,weight_in_kg,reach_in_cm,stance,date_of_birth,significant_strikes_landed_per_minute,significant_striking_accuracy,significant_strikes_absorbed_per_minute,significant_strike_defence,average_takedowns_landed_per_15_minutes,takedown_accuracy,takedown_defense,average_submissions_attempted_per_15_minutes
0,Robert Drysdale,NaN,7,0,0,190.50,92.99,NaN,Orthodox,1981-10-05,0.00,0.0,0.00,0.0,7.32,100.0,0.0,21.9
1,Daniel McWilliams,The Animal,15,37,0,185.42,83.91,NaN,NaN,NaN,3.36,77.0,0.00,0.0,0.00,0.0,100.0,21.6
2,Dan Molina,NaN,13,9,0,177.80,97.98,NaN,NaN,NaN,0.00,0.0,5.58,60.0,0.00,0.0,0.0,20.9
3,Paul Ruiz,NaN,7,4,0,167.64,61.23,NaN,NaN,NaN,1.40,33.0,1.40,75.0,0.00,0.0,100.0,20.9
4,Collin Huckbody,All In,8,2,0,190.50,83.91,193.04,Orthodox,1994-09-29,2.05,60.0,2.73,42.0,10.23,100.0,0.0,20.4

In [6]:
df["weight_in_kg"].isnull().sum()

np.int64(87)

In [7]:
undefeated = df[df["losses"] == 0]
undefeated.head()

,name,nickname,wins,losses,draws,height_cm,weight_in_kg,reach_in_cm,stance,date_of_birth,significant_strikes_landed_per_minute,significant_striking_accuracy,significant_strikes_absorbed_per_minute,significant_strike_defence,average_takedowns_landed_per_15_minutes,takedown_accuracy,takedown_defense,average_submissions_attempted_per_15_minutes
0,Robert Drysdale,NaN,7,0,0,190.50,92.99,NaN,Orthodox,1981-10-05,0.00,0.0,0.00,0.0,7.32,100.0,0.0,21.9
11,Bo Nickal,NaN,5,0,0,185.42,83.91,193.04,Southpaw,1996-01-14,2.76,62.0,0.55,75.0,11.04,50.0,0.0,13.8
16,AJ McKee,Mercenary,8,0,0,177.80,65.77,NaN,NaN,NaN,2.75,32.0,0.92,80.0,11.01,100.0,100.0,11.0
28,Daniel Puder,NaN,8,0,0,190.50,106.59,NaN,Orthodox,1981-10-09,2.77,68.0,1.17,38.0,1.21,50.0,81.0,9.0
55,Neiman Gracie,NaN,6,0,0,182.88,77.11,NaN,NaN,NaN,0.77,100.0,0.38,75.0,5.77,100.0,0.0,5.8